version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  springboot-app:
    build: .
    container_name: springboot
    ports:
      - "2020:2020"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/admin
